#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## 👇 Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## 👇 Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: payvc-core-service
    env: node
    plan: starter
    rootDir: packages/docs
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: pnpm db-seed
    buildCommand: yarn install; yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payvc-db-dev
          property: connectionString

databases:
  - name: payvc-db-dev
    plan: free
